/** Quiet Authority assessment content: score-free source questions shared by applicant and Admin views. */
export type AssessmentOption = { id: string; label: string; text: string };
export type AssessmentQuestion = { id: string; category: string; question: string; options: readonly AssessmentOption[] };

export const DEFAULT_BUSINESS_DEVELOPMENT_ASSESSMENT_QUESTIONS: readonly AssessmentQuestion[] = [
  { id: "bd-experience", category: "Business Development Experience", question: "Which statement best describes your experience in Business Development?", options: [{ id: "a", label: "A", text: "I have not worked directly in Business Development before." }, { id: "b", label: "B", text: "I have supported Business Development activities or worked in a closely related commercial role." }, { id: "c", label: "C", text: "Business Development has been a meaningful part of my role and I have independently handled some responsibilities." }, { id: "d", label: "D", text: "Business Development has been one of my primary responsibilities." }, { id: "e", label: "E", text: "Business Development is my core area of experience and I have owned significant new-business responsibilities." }] },
  { id: "prospecting", category: "Prospecting", question: "You identify a potential client that appears to be a strong fit, but you have no existing relationship with anyone in the organisation. What would you most likely do first?", options: [{ id: "a", label: "A", text: "Send a general company brochure to the organisation's public email address." }, { id: "b", label: "B", text: "Identify the relevant decision-maker and send a standard introductory message." }, { id: "c", label: "C", text: "Research the organisation, identify the likely decision-maker and develop a tailored reason for reaching out." }, { id: "d", label: "D", text: "Wait until someone can introduce me to the organisation." }, { id: "e", label: "E", text: "Add the organisation to my prospect list and revisit it when I have more time." }] },
  { id: "pipeline-management", category: "Pipeline Management", question: "A prospect has shown interest in your offer but has repeatedly delayed the next meeting. What would you most likely do?", options: [{ id: "a", label: "A", text: "Continue sending reminders until the prospect responds." }, { id: "b", label: "B", text: "Stop following up because the prospect is probably no longer interested." }, { id: "c", label: "C", text: "Reassess the opportunity, identify the likely reason for the delay and make the next follow-up specific and useful." }, { id: "d", label: "D", text: "Ask my manager to contact the prospect instead." }, { id: "e", label: "E", text: "Immediately offer a discount to encourage the prospect to proceed." }] },
  { id: "commercial-judgement", category: "Commercial Judgement", question: "A potential client asks for a significant price reduction before they will consider your proposal. What would you most likely do?", options: [{ id: "a", label: "A", text: "Agree immediately so the opportunity is not lost." }, { id: "b", label: "B", text: "Refuse because the original price has already been set." }, { id: "c", label: "C", text: "Understand what is driving the request, protect the value of the offer and explore whether scope or commercial terms can be adjusted." }, { id: "d", label: "D", text: "Reduce the price and make up the difference on a future engagement." }, { id: "e", label: "E", text: "Ask the client what price they want and accept it if it is reasonable." }] },
  { id: "client-relationship-management", category: "Client Relationship Management", question: "An existing client tells you that they are dissatisfied with part of the service your organisation delivered. What would you most likely do first?", options: [{ id: "a", label: "A", text: "Explain that the delivery team is responsible for resolving the issue." }, { id: "b", label: "B", text: "Listen carefully, clarify the issue and take ownership of coordinating the appropriate response." }, { id: "c", label: "C", text: "Offer the client a discount immediately." }, { id: "d", label: "D", text: "Defend the organisation's position so the client understands what happened." }, { id: "e", label: "E", text: "Wait for the client to submit a formal complaint before taking action." }] },
];
