/**
 * Legacy in-memory framework question set (LEGACY mock source).
 *
 * As of Task 24C-2 the Admin Question Bank CRUD reads/writes TiDB and no longer
 * consumes this module. It remains the input for the v2 Scoring Preview and the
 * Assessment Builder/Detail (Task 24C-3), which have not yet been cut over.
 */
import type { AdminQuestionOption, NumericBand, QuestionBankQuestion, QuestionConfig, RubricAnchor } from "@/lib/questionBankData";

const DRAFT_ASSESSMENT_NAME = "Business Development Officer Assessment v2 — Draft";
const DIMENSION_LABELS = { D1: "Business Development Track Record", D2: "Verified Commercial Results", D3: "Sector & Segment Relevance", D4: "Abuja Market Access", D5: "Commercial Judgement", D6: "Communication & Proposal Quality", D7: "Drive & Resilience", D8: "Tools & Digital Fluency" } as const;
const option = (id: string, text: string, rawPoints?: number, extra: Partial<AdminQuestionOption> = {}): AdminQuestionOption => ({ id, label: id.toUpperCase(), text, ...(rawPoints === undefined ? {} : { rawPoints }), ...extra });
const bands = (...items: Array<[string, number, number | undefined, number]>): NumericBand[] => items.map(([id, lowerBound, upperBound, rawPoints]) => ({ id, lowerBound, ...(upperBound === undefined ? {} : { upperBound }), rawPoints }));
const ordinal = (options: AdminQuestionOption[]): QuestionConfig => ({ ordinalConfig: { options } });
const numeric = (mode: "single" | "twoValueDerived" | "calendarYearExperience", inputs: Array<{ label: string; unit: string }>, scoringBands: NumericBand[], crossCheck?: QuestionConfig["crossCheck"]): QuestionConfig => ({ numericConfig: { mode, inputs, bands: scoringBands }, ...(crossCheck ? { crossCheck } : {}) });
const multi = (options: AdminQuestionOption[]): QuestionConfig => ({ multiConfig: { options, scoreCap: 5 } });
const sjt = (options: AdminQuestionOption[]): QuestionConfig => ({ sjtConfig: { options } });
const open = (rubric: RubricAnchor[], timeLimitSec: number, wordLimit?: number, evidenceRef?: string, crossCheck?: QuestionConfig["crossCheck"]): QuestionConfig => ({ openConfig: { pasteAllowed: false, timeLimitSec, ...(wordLimit === undefined ? {} : { wordLimit }), rubric }, ...(evidenceRef ? {} : {}), ...(crossCheck ? { crossCheck } : {}) });
const evidence = (pairedQuestionRef: string, options: AdminQuestionOption[]): QuestionConfig => ({ evidenceConfig: { pairedQuestionRef, options } });
const base = (id: string, reference: string, dimension: "D1" | "D2" | "D3" | "D4" | "D5" | "D6" | "D7" | "D8", type: QuestionBankQuestion["type"], qWeight: 1 | 2 | 3 | null, prompt: string, config: QuestionConfig, extras: Partial<QuestionBankQuestion> = {}): QuestionBankQuestion => ({ id, reference, dimension, dimensionLabel: DIMENSION_LABELS[dimension], type, qWeight, max: qWeight === null ? null : 5, required: true, prompt, helpText: "", status: "Active", evidenceRef: "", flagIf: "", timeLimitSec: null, usedIn: DRAFT_ASSESSMENT_NAME, config, competency: DIMENSION_LABELS[dimension], question: prompt, options: [], ...extras });

const d1q1Options = [
  option("a", "It has been the core of my career — most of my working life spent personally carrying a new-revenue target", 5),
  option("b", "I have done it for part of my career, carrying a target in a dedicated sales or Business Development role", 3),
  option("c", "I supported the sales function — proposals, coordination, reporting — but never owned a target myself", 1),
  option("d", "It is not my background, but it is a field I am excited to move into", undefined, { outcome: "close", relatedGate: "G3" }),
];
const d2q1Rubric: RubricAnchor[] = [
  { id: "5", points: 5, anchor: "Names the client, gives a figure with a currency and period, and describes a specific route in — a named contact, referral chain, tender or event — plus what closed it." },
  { id: "4", points: 4, anchor: "Names the client and figure with a credible route, but the route is thin on mechanism." },
  { id: "3", points: 3, anchor: "Describes a real account and route but withholds or gives only a vague value, such as ‘a significant contract’." },
  { id: "2", points: 2, anchor: "Generic response such as ‘a large multinational’ or ‘through networking’, with no client, figure or mechanism." },
  { id: "0-1", points: 1, anchor: "0–1 points: Off-question, describes an account the candidate inherited rather than opened, or is plainly generic filler." },
];
const d4q2Rubric: RubricAnchor[] = [
  { id: "5", points: 5, anchor: "A precise, plausible title such as Head of Administration, Facilities Manager, Protocol Officer or Country Operations Manager, and a specific origin such as a deal, project or named introduction." },
  { id: "3", points: 3, anchor: "A plausible title but a vague origin such as ‘we've known each other for years’." },
  { id: "1", points: 1, anchor: "A vague title such as ‘a senior person’ or ‘management’, or an origin that describes an acquaintance rather than a working relationship." },
  { id: "0", points: 0, anchor: "Cannot name a role, or the response contradicts the selection in D4.Q1." },
];
const d6q1Rubric: RubricAnchor[] = [
  { id: "5", points: 5, anchor: "Opens on the reader's situation rather than the sender's; gives one concrete reason to care tied to extended stays, postings or costs; makes one clear ask; remains within the word limit; and contains no errors." },
  { id: "4", points: 4, anchor: "Specific and well written, but the ask is soft or the response opens with Peniel rather than the reader." },
  { id: "3", points: 3, anchor: "Professional and correct, but generic enough that it could have been sent by any hotel in the city." },
  { id: "2", points: 2, anchor: "Over-length, salesy, or opens with ‘I hope this email finds you well’ followed by a company description." },
  { id: "0-1", points: 1, anchor: "0–1 points: Contains errors, is off-brief, or is generic boilerplate." },
];

export const FRAMEWORK_QUESTIONS: readonly QuestionBankQuestion[] = [
  base("framework-d1-q1", "D1.Q1", "D1", "ORDINAL", 3, "Which of these best describes your business development experience?", ordinal(d1q1Options), { options: d1q1Options }),
  base("framework-d3-q1", "D3.Q1", "D3", "MULTI", 3, "Which of the following have you personally sold to a paying client? Select all that apply.", multi([
    option("a", "Corporate accommodation or extended-stay contracts", 3), option("b", "Embassy, diplomatic mission or international NGO contracts", 3), option("c", "Hotel rooms, event space or food & beverage", 2), option("d", "Government or public-sector contracts", 2), option("e", "Real estate leasing or property rental", 2), option("f", "Airline crew or rotational-worker accommodation", 2), option("g", "Facility management or corporate support services", 1), option("h", "Hospitality REIT investment products", -1, { decoy: true }), option("i", "Timeshare memberships in Abuja", -1, { decoy: true }),
  ]), { options: [
    option("a", "Corporate accommodation or extended-stay contracts", 3), option("b", "Embassy, diplomatic mission or international NGO contracts", 3), option("c", "Hotel rooms, event space or food & beverage", 2), option("d", "Government or public-sector contracts", 2), option("e", "Real estate leasing or property rental", 2), option("f", "Airline crew or rotational-worker accommodation", 2), option("g", "Facility management or corporate support services", 1), option("h", "Hospitality REIT investment products", -1, { decoy: true }), option("i", "Timeshare memberships in Abuja", -1, { decoy: true }),
  ] }),
  base("framework-d2-q3", "D2.Q3", "D2", "ORDINAL", 1, "How would you describe your overall record against target?", ordinal([
    option("a", "I consistently exceeded my targets", 5), option("b", "I consistently met my targets and exceeded them in some years", 4), option("c", "I met my targets most years", 3), option("d", "I met them in some years and missed in others", 2), option("e", "I never carried a formal target", 0),
  ]), { options: [option("a", "I consistently exceeded my targets", 5), option("b", "I consistently met my targets and exceeded them in some years", 4), option("c", "I met my targets most years", 3), option("d", "I met them in some years and missed in others", 2), option("e", "I never carried a formal target", 0)], flagIf: "Candidate selects ‘I consistently exceeded my targets’ while D2.Q2 derives attainment below 100%.", config: { ...ordinal([option("a", "I consistently exceeded my targets", 5), option("b", "I consistently met my targets and exceeded them in some years", 4), option("c", "I met my targets most years", 3), option("d", "I met them in some years and missed in others", 2), option("e", "I never carried a formal target", 0)]), crossCheck: { compareQuestionRef: "D2.Q2", ruleDescription: "Candidate selects ‘I consistently exceeded my targets’ while D2.Q2 derives attainment below 100%.", flagOutcome: "integrity" } } }),
  base("framework-d4-q1", "D4.Q1", "D4", "MULTI", 2, "In Abuja specifically, which of these do you currently have a working relationship with — an organisation where you could call someone this week and get a meeting?", multi([
    option("a", "An embassy or high commission", 3), option("b", "An international NGO, UN agency or development organisation", 3), option("c", "An oil, gas or energy company", 2), option("d", "A federal ministry, agency or parastatal", 2), option("e", "A travel management company or relocation agent", 2), option("f", "A bank or financial institution", 1), option("g", "A large church or faith organisation", 1), option("h", "The Abuja Serviced Apartment Owners' Association", -1, { decoy: true }),
  ]), { options: [option("a", "An embassy or high commission", 3), option("b", "An international NGO, UN agency or development organisation", 3), option("c", "An oil, gas or energy company", 2), option("d", "A federal ministry, agency or parastatal", 2), option("e", "A travel management company or relocation agent", 2), option("f", "A bank or financial institution", 1), option("g", "A large church or faith organisation", 1), option("h", "The Abuja Serviced Apartment Owners' Association", -1, { decoy: true })] }),
  base("framework-d4-q2", "D4.Q2", "D4", "OPEN", 3, "Take one of the organisations you just selected. What is the job title of the person you would call, and how did that relationship start?", open(d4q2Rubric, 60), { timeLimitSec: 60, flagIf: "Integrity flag where materially contradictory to D4.Q1.", config: { openConfig: { pasteAllowed: false, timeLimitSec: 60, rubric: d4q2Rubric }, crossCheck: { compareQuestionRef: "D4.Q1", ruleDescription: "Integrity flag where materially contradictory.", flagOutcome: "integrity" } } }),
  base("framework-d3-q3", "D3.Q3", "D3", "ORDINAL", 3, "Across your selling career, roughly what share of the revenue you brought in came from selling to organisations — companies, institutions, embassies, NGOs, agencies, churches — rather than to individuals?", ordinal([
    option("a", "80% or more — organisations are what I sell to", 5), option("b", "Between half and 80%", 4), option("c", "Roughly an even split", 3), option("d", "Under half — mostly individuals or high-net-worth private clients", 1), option("e", "I have only ever sold to individuals", 0),
  ]), { options: [option("a", "80% or more — organisations are what I sell to", 5), option("b", "Between half and 80%", 4), option("c", "Roughly an even split", 3), option("d", "Under half — mostly individuals or high-net-worth private clients", 1), option("e", "I have only ever sold to individuals", 0)] }),
  base("framework-d5-q1", "D5.Q1", "D5", "SJT", 3, "A corporate client is weighing a three-month posting at Peniel against a four-star hotel quoting a similar nightly rate. What is your strongest commercial argument?", sjt([
    option("a", "Total cost of the posting: the kitchen and in-unit laundry remove most per-diem meal and laundry spend, and a two-bedroom houses two colleagues on one rate", 5, { whatThisReveals: "Understands extended-stay economics and sells against the client's total spend rather than the nightly rate." }), option("b", "The apartment is significantly larger and more comfortable than a hotel room", 2, { whatThisReveals: "Sells product features rather than the client's economics." }), option("c", "Peniel has operated in Abuja for more than twenty years and is a trusted name", 1, { whatThisReveals: "Uses heritage as reassurance but does not answer the client's commercial decision." }), option("d", "Offer to match or beat the hotel's rate", -2, { whatThisReveals: "Concedes rate instead of defending the economic value of the serviced-apartment offer." }),
  ]), { options: [option("a", "Total cost of the posting: the kitchen and in-unit laundry remove most per-diem meal and laundry spend, and a two-bedroom houses two colleagues on one rate", 5, { whatThisReveals: "Understands extended-stay economics and sells against the client's total spend rather than the nightly rate." }), option("b", "The apartment is significantly larger and more comfortable than a hotel room", 2, { whatThisReveals: "Sells product features rather than the client's economics." }), option("c", "Peniel has operated in Abuja for more than twenty years and is a trusted name", 1, { whatThisReveals: "Uses heritage as reassurance but does not answer the client's commercial decision." }), option("d", "Offer to match or beat the hotel's rate", -2, { whatThisReveals: "Concedes rate instead of defending the economic value of the serviced-apartment offer." })] }),
  base("framework-d2-q1", "D2.Q1", "D2", "OPEN", 3, "Name the largest new account you personally opened: who the client was, roughly what it was worth per year, and how you got in.", open(d2q1Rubric, 90), { timeLimitSec: 90, evidenceRef: "D2.Q1E", config: { openConfig: { pasteAllowed: false, timeLimitSec: 90, rubric: d2q1Rubric } } }),
  base("framework-d2-q1e", "D2.Q1E", "D2", "EVIDENCE", null, "Can the account you just described be confirmed by someone we could contact?", evidence("D2.Q1", [option("a", "Yes — I can provide a named referee and their contact details", undefined, { verificationMultiplier: 1 }), option("b", "Yes — my former employer can confirm it, but I have no individual referee", undefined, { verificationMultiplier: 0.95 }), option("c", "No — I would rather not have this verified", undefined, { verificationMultiplier: 0.85 })]), { max: null, evidenceRef: "D2.Q1", options: [option("a", "Yes — I can provide a named referee and their contact details", undefined, { verificationMultiplier: 1 }), option("b", "Yes — my former employer can confirm it, but I have no individual referee", undefined, { verificationMultiplier: 0.95 }), option("c", "No — I would rather not have this verified", undefined, { verificationMultiplier: 0.85 })] }),
  base("framework-d7-q1", "D7.Q1", "D7", "SJT", 3, "You have approached a target corporate account six times over three months — calls, emails, a drop-in — with no response at all. What do you do next?", sjt([
    option("a", "Change the entry point — approach a different function such as facilities, HR mobility or procurement with a different hook", 5, { whatThisReveals: "Understands that silence can mean the wrong door rather than the wrong account." }), option("b", "Ask an existing client or partner for a warm referral into the organisation", 4, { whatThisReveals: "Strong instinct but dependent on another person's goodwill." }), option("c", "Put it on a long nurture cadence and move the hours to accounts that are moving", 2, { whatThisReveals: "Disciplined but passive while building a pipeline." }), option("d", "Send a final email offering a rate below the published corporate rate to force a reply", -2, { whatThisReveals: "Attempts to buy attention with margin and creates a damaging commercial precedent." }),
  ]), { options: [option("a", "Change the entry point — approach a different function such as facilities, HR mobility or procurement with a different hook", 5, { whatThisReveals: "Understands that silence can mean the wrong door rather than the wrong account." }), option("b", "Ask an existing client or partner for a warm referral into the organisation", 4, { whatThisReveals: "Strong instinct but dependent on another person's goodwill." }), option("c", "Put it on a long nurture cadence and move the hours to accounts that are moving", 2, { whatThisReveals: "Disciplined but passive while building a pipeline." }), option("d", "Send a final email offering a rate below the published corporate rate to force a reply", -2, { whatThisReveals: "Attempts to buy attention with margin and creates a damaging commercial precedent." })] }),
  base("framework-d1-q2", "D1.Q2", "D1", "NUMERIC", 2, "In which calendar year did you first personally carry a new-business target?", numeric("calendarYearExperience", [{ label: "Calendar year", unit: "year" }], bands(["5-plus", 5, undefined, 5], ["3-4", 3, 4, 3], ["1-2", 1, 2, 1], ["never", 0, 0, 0]), { compareQuestionRef: "D1.Q1", ruleDescription: "Derived years disagree with the D1.Q1 self-description by more than two years.", flagOutcome: "integrity" }), { flagIf: "Integrity flag: derived years disagree with D1.Q1 by more than two years.", config: numeric("calendarYearExperience", [{ label: "Calendar year", unit: "year" }], bands(["5-plus", 5, undefined, 5], ["3-4", 3, 4, 3], ["1-2", 1, 2, 1], ["never", 0, 0, 0]), { compareQuestionRef: "D1.Q1", ruleDescription: "Derived years disagree with the D1.Q1 self-description by more than two years.", flagOutcome: "integrity" }) }),
  base("framework-d6-q1", "D6.Q1", "D6", "OPEN", 3, "Write the opening of an email to the Head of Administration at an embassy in Abuja who has never heard of Peniel. Sixty words maximum.", open(d6q1Rubric, 90, 60), { timeLimitSec: 90, config: { openConfig: { pasteAllowed: false, timeLimitSec: 90, wordLimit: 60, rubric: d6q1Rubric } } }),
  base("framework-d8-q1", "D8.Q1", "D8", "MULTI", 2, "Which of these have you used regularly in a work setting?", multi([
    option("a", "A CRM — Salesforce, HubSpot, Zoho or similar", 2), option("b", "A property management or booking system — Opera, eZee, Cloudbeds or similar", 2), option("c", "Excel or Sheets to build and track a pipeline forecast", 2), option("d", "OTA extranets — Booking.com, Expedia, Agoda", 1), option("e", "LinkedIn Sales Navigator or similar prospecting tools", 1), option("f", "Writing formal proposals or tender responses", 1), option("g", "Peniel Connect CRM", -1, { decoy: true }),
  ]), { options: [option("a", "A CRM — Salesforce, HubSpot, Zoho or similar", 2), option("b", "A property management or booking system — Opera, eZee, Cloudbeds or similar", 2), option("c", "Excel or Sheets to build and track a pipeline forecast", 2), option("d", "OTA extranets — Booking.com, Expedia, Agoda", 1), option("e", "LinkedIn Sales Navigator or similar prospecting tools", 1), option("f", "Writing formal proposals or tender responses", 1), option("g", "Peniel Connect CRM", -1, { decoy: true })] }),
  base("framework-d2-q2", "D2.Q2", "D2", "NUMERIC", 3, "In your last full year carrying a target: what was the target, and what did you actually deliver? Enter both figures.", numeric("twoValueDerived", [{ label: "Target", unit: "currency" }, { label: "Actual delivered", unit: "currency" }], bands(["110-plus", 110, undefined, 5], ["100-109", 100, 109, 4], ["90-99", 90, 99, 3], ["70-89", 70, 89, 1], ["below-70", 0, 69, 0])), { config: numeric("twoValueDerived", [{ label: "Target", unit: "currency" }, { label: "Actual delivered", unit: "currency" }], bands(["110-plus", 110, undefined, 5], ["100-109", 100, 109, 4], ["90-99", 90, 99, 3], ["70-89", 70, 89, 1], ["below-70", 0, 69, 0])) }),
];

export const FRAMEWORK_QUESTION_IDS = FRAMEWORK_QUESTIONS.map((question) => question.id);
export const FRAMEWORK_QUESTION_REFERENCES = FRAMEWORK_QUESTIONS.map((question) => question.reference);
export const FRAMEWORK_DRAFT_ORDER = ["D1.Q1", "D3.Q1", "D2.Q3", "D4.Q1", "D4.Q2", "D3.Q3", "D5.Q1", "D2.Q1", "D2.Q1E", "D7.Q1", "D1.Q2", "D6.Q1", "D8.Q1", "D2.Q2"] as const;
