/**
 * Quiet Authority Question Bank data: a frontend-only administrative index that derives assigned applicant questions from the shared assessment schema without scores or evaluation fields.
 */
import { BUSINESS_DEVELOPMENT_ASSESSMENT_QUESTIONS, type AssessmentOption } from "@/lib/assessmentData";

export type QuestionType = "Experience" | "Scenario";
export type QuestionStatus = "Active" | "Inactive";
export type QuestionBankQuestion = { id: string; reference: string; competency: string; type: QuestionType; question: string; options: readonly AssessmentOption[]; status: QuestionStatus; usedIn: string };
const assessmentName = "Business Development Assessment";
const standardOptions = (choices: readonly string[]): readonly AssessmentOption[] => choices.map((text, index) => ({ id: String.fromCharCode(97 + index), label: String.fromCharCode(65 + index), text }));
const existingQuestionTypes: QuestionType[] = ["Experience", "Scenario", "Scenario", "Scenario", "Scenario"];

export const QUESTION_BANK_QUESTIONS: readonly QuestionBankQuestion[] = [
  ...BUSINESS_DEVELOPMENT_ASSESSMENT_QUESTIONS.map((question, index) => ({ id: `q-${String(index + 1).padStart(3, "0")}`, reference: `Q-${String(index + 1).padStart(3, "0")}`, competency: question.category, type: existingQuestionTypes[index], question: question.question, options: question.options, status: "Active" as const, usedIn: assessmentName })),
  { id: "q-006", reference: "Q-006", competency: "Negotiation & Closing", type: "Scenario", question: "A prospect says they are ready to proceed but asks for a final concession that could affect the commercial value of the opportunity. What would you most likely do?", options: standardOptions(["Agree immediately to avoid losing the opportunity.", "Clarify the underlying concern, protect the agreed value and explore an appropriate commercial trade-off.", "End the conversation because the prospect is changing the terms.", "Refer every request to a senior colleague without further discussion.", "Offer several concessions before understanding the request."]), status: "Active", usedIn: "Not assigned" },
  { id: "q-007", reference: "Q-007", competency: "Communication", type: "Experience", question: "Which statement best describes how you communicate the value of a new product or service to a prospective client?", options: standardOptions(["I provide the same overview to every prospect.", "I focus mainly on the product features.", "I connect the offer to the prospect's priorities and confirm that the value is understood.", "I avoid discussing value until the client requests pricing.", "I rely on written materials instead of conversations."]), status: "Active", usedIn: "Not assigned" },
  { id: "q-008", reference: "Q-008", competency: "Leadership", type: "Scenario", question: "A colleague is struggling to move several opportunities forward. What would you most likely do first?", options: standardOptions(["Take over all of the opportunities immediately.", "Review the pipeline together, identify the blockers and agree practical next steps.", "Tell the colleague to increase the number of follow-up emails.", "Wait for the next reporting cycle before discussing it.", "Raise the issue publicly in a team meeting."]), status: "Active", usedIn: "Not assigned" },
  { id: "q-009", reference: "Q-009", competency: "Prospecting", type: "Experience", question: "How do you typically prioritise potential business development opportunities when your pipeline includes several different organisations?", options: standardOptions(["I contact prospects in the order they appear in my list.", "I prioritise the most familiar brands.", "I assess fit, potential value, urgency and access to the relevant decision-makers.", "I focus only on organisations that contact me first.", "I choose whichever prospect appears easiest to reach."]), status: "Active", usedIn: "Not assigned" },
  { id: "q-010", reference: "Q-010", competency: "Pipeline Management", type: "Scenario", question: "An opportunity has been inactive for several weeks after a promising initial conversation. What would you most likely do?", options: standardOptions(["Remove it from the pipeline without further contact.", "Send the same follow-up message each week.", "Review the earlier discussion, identify a relevant reason to re-engage and agree a clear next step.", "Offer a discount immediately.", "Wait for the prospect to restart the conversation."]), status: "Active", usedIn: "Not assigned" },
  { id: "q-011", reference: "Q-011", competency: "Commercial Judgement", type: "Experience", question: "When evaluating a potential commercial opportunity, what information is most important to understand before committing further time?", options: standardOptions(["Whether the organisation has a well-known name.", "The likely needs, decision process, value potential and delivery feasibility.", "Whether the prospect responds quickly to messages.", "Whether competitors have already contacted the prospect.", "Whether a discount may be requested later."]), status: "Active", usedIn: "Not assigned" },
  { id: "q-012", reference: "Q-012", competency: "Business Development Experience", type: "Experience", question: "Which statement best reflects your approach to building a sustainable pipeline of new business opportunities?", options: standardOptions(["I focus only on opportunities that can close quickly.", "I rely on one lead source whenever possible.", "I maintain a balanced pipeline, qualify opportunities and build relationships over time.", "I pursue every available lead with the same level of effort.", "I wait until current opportunities are complete before prospecting again."]), status: "Active", usedIn: "Not assigned" },
];

export const QUESTION_BANK_COMPETENCIES = ["Business Development Experience", "Prospecting", "Pipeline Management", "Commercial Judgement", "Client Relationship Management", "Negotiation & Closing", "Communication", "Leadership"] as const;
export function getQuestionBankQuestion(id: string) { return QUESTION_BANK_QUESTIONS.find((question) => question.id === id); }
export function getQuestionBankSummary() { return { total: QUESTION_BANK_QUESTIONS.length, active: QUESTION_BANK_QUESTIONS.filter((question) => question.status === "Active").length, competencies: QUESTION_BANK_COMPETENCIES.length }; }
