/**
 * Quiet Authority Recruitment Roles list: a restrained frontend-only management surface for role setup, local search, and status review.
 */
import { AdminShell } from "@/components/admin/AdminShell";
import { FoundationButton, FoundationInput, FoundationSelect, StatusBadge } from "@/components/foundation/ui";
import { getRecruitmentRoles, type RecruitmentRole, type RoleStatus } from "@/lib/adminRoleData";
import { Search } from "lucide-react";
import { useMemo, useState } from "react";
import { useLocation } from "wouter";

const statusOptions: RoleStatus[] = ["Draft", "Open", "Closed", "Archived"];
function RoleCell({ role }: { role: RecruitmentRole }) { return <div><p className="font-medium text-primary">{role.title}</p><p className="mt-1 text-[12px] text-muted-foreground">{role.employmentType}</p></div>; }

export default function AdminRoles() {
  const [, setLocation] = useLocation();
  const [roles] = useState(() => getRecruitmentRoles());
  const [search, setSearch] = useState("");
  const [status, setStatus] = useState("all");
  const normalisedSearch = search.trim().toLowerCase();
  const visibleRoles = useMemo(() => roles.filter((role) => (!normalisedSearch || [role.title, role.department, role.location].some((value) => value.toLowerCase().includes(normalisedSearch))) && (status === "all" || role.status === status)), [normalisedSearch, roles, status]);
  const hasActiveFilters = Boolean(normalisedSearch) || status !== "all";
  const resetFilters = () => { setSearch(""); setStatus("all"); };
  const openRoles = roles.filter((role) => role.status === "Open").length;
  const draftRoles = roles.filter((role) => role.status === "Draft").length;
  return <AdminShell title="Recruitment Roles"><section className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[12px] font-medium text-muted-foreground">Recruitment setup</p><h2 className="mt-2 text-3xl font-semibold tracking-[-0.035em] text-primary">Recruitment Roles</h2><p className="mt-2 max-w-2xl text-[15px] leading-6 text-muted-foreground">Create and manage the roles applicants can apply for through the recruitment portal.</p></div><FoundationButton onClick={() => setLocation("/admin/roles/new")}>Create role</FoundationButton></section>
    <section className="mt-6 grid gap-3 sm:grid-cols-3" aria-label="Role summary"><article className="rounded-xl border border-border bg-white p-4"><p className="text-[12px] font-medium text-muted-foreground">Total Roles</p><p className="mt-2 text-2xl font-semibold tracking-[-0.04em] text-primary">{roles.length}</p><p className="mt-1.5 text-[12px] text-muted-foreground">Across all statuses</p></article><article className="rounded-xl border border-border bg-white p-4"><p className="text-[12px] font-medium text-muted-foreground">Open Roles</p><p className="mt-2 text-2xl font-semibold tracking-[-0.04em] text-primary">{openRoles}</p><p className="mt-1.5 text-[12px] text-muted-foreground">Currently accepting applications</p></article><article className="rounded-xl border border-border bg-white p-4"><p className="text-[12px] font-medium text-muted-foreground">Draft Roles</p><p className="mt-2 text-2xl font-semibold tracking-[-0.04em] text-primary">{draftRoles}</p><p className="mt-1.5 text-[12px] text-muted-foreground">Not yet published</p></article></section>
    <section className="mt-6 rounded-xl border border-border bg-white p-4 sm:p-5 lg:p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div className="relative w-full sm:max-w-sm"><label className="sr-only" htmlFor="role-search">Search roles</label><Search className="pointer-events-none absolute left-3.5 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><FoundationInput className="pl-10" id="role-search" onChange={(event) => setSearch(event.target.value)} placeholder="Search roles" value={search} /></div><div className="w-full sm:w-[190px]"><label className="mb-1.5 block text-[12px] font-medium text-muted-foreground" htmlFor="role-status-filter">Status</label><FoundationSelect id="role-status-filter" onChange={(event) => setStatus(event.target.value)} value={status}><option value="all">All statuses</option>{statusOptions.map((item) => <option key={item} value={item}>{item}</option>)}</FoundationSelect></div></div><div className="mt-5 flex items-center justify-between gap-4 border-t border-border pt-4"><p className="text-[13px] text-muted-foreground">{visibleRoles.length} {visibleRoles.length === 1 ? "role" : "roles"}</p>{hasActiveFilters ? <button className="text-[13px] font-medium text-portal-blue transition-colors hover:text-primary hover:underline" onClick={resetFilters} type="button">Clear filters</button> : null}</div>
      {visibleRoles.length ? <><div className="mt-3 hidden overflow-x-auto md:block"><table className="w-full min-w-[900px] text-left"><thead className="border-b border-border"><tr>{["Role", "Department", "Location", "Applications", "Status", "Last Updated", "Action"].map((heading) => <th className="px-3 py-3 text-[11px] font-semibold uppercase tracking-[0.08em] text-muted-foreground last:text-right" key={heading}>{heading}</th>)}</tr></thead><tbody className="divide-y divide-border">{visibleRoles.map((role) => <tr key={role.id}><td className="px-3 py-4 text-sm"><RoleCell role={role} /></td><td className="px-3 py-4 text-[13px] text-muted-foreground">{role.department}</td><td className="px-3 py-4 text-[13px] text-muted-foreground">{role.location}</td><td className="px-3 py-4 text-[13px] text-primary">{role.applicationCount}</td><td className="px-3 py-4"><StatusBadge status={role.status} /></td><td className="whitespace-nowrap px-3 py-4 text-[13px] text-muted-foreground">{role.lastUpdatedLabel}</td><td className="px-3 py-4 text-right"><button className="text-[13px] font-medium text-portal-blue transition-colors hover:text-primary hover:underline" onClick={() => setLocation(`/admin/roles/${role.slug}`)} type="button">View</button></td></tr>)}</tbody></table></div><div className="mt-3 divide-y divide-border md:hidden">{visibleRoles.map((role) => <article className="py-4" key={role.id}><RoleCell role={role} /><div className="mt-4 grid grid-cols-2 gap-x-4 gap-y-4"><div><p className="text-[11px] font-semibold uppercase tracking-[0.08em] text-muted-foreground">Department</p><p className="mt-1 text-[13px] text-primary">{role.department}</p></div><div><p className="text-[11px] font-semibold uppercase tracking-[0.08em] text-muted-foreground">Location</p><p className="mt-1 text-[13px] text-primary">{role.location}</p></div><div><p className="text-[11px] font-semibold uppercase tracking-[0.08em] text-muted-foreground">Applications</p><p className="mt-1 text-[13px] text-primary">{role.applicationCount}</p></div><div><p className="text-[11px] font-semibold uppercase tracking-[0.08em] text-muted-foreground">Status</p><div className="mt-1.5"><StatusBadge status={role.status} /></div></div></div><button className="mt-4 text-[13px] font-medium text-portal-blue transition-colors hover:text-primary hover:underline" onClick={() => setLocation(`/admin/roles/${role.slug}`)} type="button">View role</button></article>)}</div></> : <div className="py-14 text-center"><h3 className="text-base font-semibold text-primary">No roles found</h3><p className="mt-2 text-sm text-muted-foreground">Try changing your search or filter.</p><button className="mt-4 text-[13px] font-medium text-portal-blue transition-colors hover:text-primary hover:underline" onClick={resetFilters} type="button">Clear filters</button></div>}</section>
  </AdminShell>;
}
