/**
 * Quiet Authority Recruitment Role detail: a reusable, evidence-led Admin role view with editable local setup, a compact application subset, and no assessment configuration.
 */
import { AdminShell } from "@/components/admin/AdminShell";
import { FoundationButton, StatusBadge } from "@/components/foundation/ui";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { getAdminApplications } from "@/lib/adminMockData";
import { BUSINESS_DEVELOPMENT_MANAGER_ROLE_ID, formatRoleDate, getRecruitmentRole } from "@/lib/adminRoleData";
import { ArrowLeft, Pencil } from "lucide-react";
import { useLocation, useRoute } from "wouter";

function OverviewTab({ role }: { role: NonNullable<ReturnType<typeof getRecruitmentRole>> }) {
  return <div className="grid gap-6 lg:grid-cols-[minmax(0,68fr)_minmax(260px,32fr)]"><article className="rounded-xl border border-border bg-white p-5 shadow-none sm:p-6"><h3 className="text-lg font-semibold tracking-[-0.02em] text-primary">Role information</h3><section className="mt-6"><h4 className="text-[12px] font-semibold uppercase tracking-[0.09em] text-muted-foreground">Short description</h4><p className="mt-3 max-w-3xl text-sm leading-6 text-primary">{role.shortDescription}</p></section><dl className="mt-6 grid gap-x-6 gap-y-5 border-t border-border pt-6 sm:grid-cols-2"><div><dt className="text-[12px] text-muted-foreground">Department</dt><dd className="mt-1 text-sm font-medium text-primary">{role.department}</dd></div><div><dt className="text-[12px] text-muted-foreground">Location</dt><dd className="mt-1 text-sm font-medium text-primary">{role.location}</dd></div><div><dt className="text-[12px] text-muted-foreground">Employment type</dt><dd className="mt-1 text-sm font-medium text-primary">{role.employmentType}</dd></div><div><dt className="text-[12px] text-muted-foreground">Application opening date</dt><dd className="mt-1 text-sm font-medium text-primary">{formatRoleDate(role.openingDate)}</dd></div><div><dt className="text-[12px] text-muted-foreground">Application closing date</dt><dd className="mt-1 text-sm font-medium text-primary">{formatRoleDate(role.closingDate)}</dd></div><div><dt className="text-[12px] text-muted-foreground">Last updated</dt><dd className="mt-1 text-sm font-medium text-primary">{role.lastUpdatedLabel}</dd></div></dl>{role.fullDescription ? <section className="mt-6 border-t border-border pt-6"><h4 className="text-[12px] font-semibold uppercase tracking-[0.09em] text-muted-foreground">Role description</h4><p className="mt-3 whitespace-pre-wrap text-sm leading-6 text-primary">{role.fullDescription}</p></section> : null}</article><article className="h-fit rounded-xl border border-border bg-white p-5 shadow-none"><h3 className="text-lg font-semibold tracking-[-0.02em] text-primary">Role summary</h3><dl className="mt-5 space-y-4"><div><dt className="text-[12px] text-muted-foreground">Status</dt><dd className="mt-1.5"><StatusBadge status={role.status} /></dd></div><div><dt className="text-[12px] text-muted-foreground">Applications</dt><dd className="mt-1 text-sm font-medium text-primary">{role.applicationCount}</dd></div><div><dt className="text-[12px] text-muted-foreground">Submitted</dt><dd className="mt-1 text-sm font-medium text-primary">{role.submittedCount}</dd></div><div><dt className="text-[12px] text-muted-foreground">In Progress</dt><dd className="mt-1 text-sm font-medium text-primary">{role.inProgressCount}</dd></div><div><dt className="text-[12px] text-muted-foreground">Assessment</dt><dd className="mt-1 text-sm font-medium text-primary">Not yet configured</dd></div></dl></article></div>;
}

function ApplicationsTab({ roleId, onViewAll, onViewCandidate }: { roleId: string; onViewAll: () => void; onViewCandidate: (id: string) => void }) {
  const applications = roleId === BUSINESS_DEVELOPMENT_MANAGER_ROLE_ID ? getAdminApplications() : [];
  return <section><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><h3 className="text-xl font-semibold tracking-[-0.025em] text-primary">Applications</h3><p className="mt-1 text-sm text-muted-foreground">Applications received for this recruitment role.</p></div>{applications.length ? <button className="text-[13px] font-medium text-portal-blue transition-colors hover:text-primary hover:underline" onClick={onViewAll} type="button">View all applications</button> : null}</div>{applications.length ? <article className="mt-5 rounded-xl border border-border bg-white p-4 shadow-none sm:p-5"><div className="hidden overflow-x-auto md:block"><table className="w-full min-w-[680px] text-left"><thead className="border-b border-border"><tr>{["Candidate", "Status", "Assessment", "Applied", "View"].map((heading) => <th className="px-3 py-3 text-[11px] font-semibold uppercase tracking-[0.08em] text-muted-foreground last:text-right" key={heading}>{heading}</th>)}</tr></thead><tbody className="divide-y divide-border">{applications.map((application) => <tr key={application.id}><td className="px-3 py-4"><p className="text-sm font-medium text-primary">{application.candidateName}</p><p className="mt-1 text-[12px] text-muted-foreground">{application.email}</p></td><td className="px-3 py-4"><StatusBadge status={application.applicationStatus} /></td><td className="px-3 py-4"><StatusBadge status={application.assessmentStatus} /></td><td className="whitespace-nowrap px-3 py-4 text-[13px] text-muted-foreground">{application.appliedDateLabel}</td><td className="px-3 py-4 text-right"><button className="text-[13px] font-medium text-portal-blue transition-colors hover:text-primary hover:underline" onClick={() => onViewCandidate(application.id)} type="button">View</button></td></tr>)}</tbody></table></div><div className="divide-y divide-border md:hidden">{applications.map((application) => <article className="py-4" key={application.id}><p className="text-sm font-medium text-primary">{application.candidateName}</p><p className="mt-1 text-[12px] text-muted-foreground">{application.email}</p><div className="mt-4 flex flex-wrap items-center gap-3"><StatusBadge status={application.applicationStatus} /><StatusBadge status={application.assessmentStatus} /><span className="text-[13px] text-muted-foreground">{application.appliedDateLabel}</span></div><button className="mt-4 text-[13px] font-medium text-portal-blue hover:underline" onClick={() => onViewCandidate(application.id)} type="button">View application</button></article>)}</div></article> : <article className="mt-5 rounded-xl border border-border bg-white p-6"><h4 className="text-base font-semibold text-primary">No applications received</h4><p className="mt-2 text-sm text-muted-foreground">Applications will appear here when candidates apply for this role.</p></article>}</section>;
}

function AssessmentTab() { return <article className="rounded-xl border border-border bg-white p-6"><h3 className="text-xl font-semibold tracking-[-0.025em] text-primary">Assessment</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">Role-specific assessment configuration will be added in a later stage.</p><div className="mt-6 border-t border-border pt-5"><h4 className="text-base font-semibold text-primary">No assessment configuration available yet</h4></div></article>; }

export default function AdminRoleDetail() {
  const [, params] = useRoute("/admin/roles/:roleSlug");
  const [location, setLocation] = useLocation();
  const slug = params?.roleSlug ?? "";
  const role = getRecruitmentRole(slug);
  if (!role) return <AdminShell title="Recruitment Roles"><section className="py-8"><h2 className="text-2xl font-semibold tracking-[-0.03em] text-primary">Role not found</h2><p className="mt-2 text-sm text-muted-foreground">The requested recruitment role could not be found.</p><FoundationButton className="mt-6" onClick={() => setLocation("/admin/roles")} variant="secondary">Back to recruitment roles</FoundationButton></section></AdminShell>;
  return <AdminShell title="Recruitment Roles"><button className="inline-flex items-center gap-2 text-[13px] font-medium text-muted-foreground transition-colors hover:text-primary" onClick={() => setLocation("/admin/roles")} type="button"><ArrowLeft className="size-4" />Back to recruitment roles</button><article className="mt-5 rounded-xl border border-border bg-white p-5 shadow-none sm:p-6"><div className="flex flex-col gap-5 sm:flex-row sm:items-start sm:justify-between"><div><h2 className="text-2xl font-semibold tracking-[-0.03em] text-primary">{role.title}</h2><div className="mt-3 flex flex-wrap items-center gap-x-4 gap-y-2 text-[13px] text-muted-foreground"><span className="font-medium text-primary">{role.department}</span><span>{role.employmentType}</span><span>Location: {role.location}</span><StatusBadge status={role.status} /></div></div><FoundationButton onClick={() => setLocation(`${location}/edit`)} variant="secondary"><Pencil className="size-4" />Edit role</FoundationButton></div></article><Tabs className="mt-6" defaultValue="overview"><div className="overflow-x-auto pb-1"><TabsList><TabsTrigger value="overview">Overview</TabsTrigger><TabsTrigger value="applications">Applications</TabsTrigger><TabsTrigger value="assessment">Assessment</TabsTrigger></TabsList></div><TabsContent value="overview"><OverviewTab role={role} /></TabsContent><TabsContent value="applications"><ApplicationsTab onViewAll={() => setLocation("/admin/applications")} onViewCandidate={(id) => setLocation(`/admin/applications/${id}`)} roleId={role.id} /></TabsContent><TabsContent value="assessment"><AssessmentTab /></TabsContent></Tabs></AdminShell>;
}
