/** Quiet Authority Assessment Detail: an evidence-led, score-value-free configuration view with exactly Overview and Questions tabs. */
import { AdminShell } from "@/components/admin/AdminShell";
import { FoundationButton, StatusBadge } from "@/components/foundation/ui";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { useAdminRoles } from "@/hooks/useRecruitmentData";
import { getAdminAssessment, getAssessmentQuestions, getAssessmentReadiness, type AdminAssessment } from "@/lib/adminAssessmentData";
import { hasQuestionConfiguration, type QuestionBankQuestion } from "@/lib/questionBankData";
import { AlertTriangle, ArrowLeft, Eye, Pencil } from "lucide-react";
import { useLocation, useRoute } from "wouter";

function ScoringState({ configured }: { configured: boolean }) { return <span className={`inline-flex rounded-md px-2.5 py-1 text-xs font-medium ${configured ? "bg-[#e9f6ee] text-status-success-strong" : "bg-[#fff8e8] text-[#765d22]"}`}>{configured ? "Configured" : "Not configured"}</span>; }
function Definition({ label, children }: { label: string; children: React.ReactNode }) { return <div><dt className="text-[12px] text-muted-foreground">{label}</dt><dd className="mt-1 text-sm font-medium text-primary">{children}</dd></div>; }

function OverviewTab({ assessment, roleTitle }: { assessment: AdminAssessment; roleTitle: string }) {
  const readiness = getAssessmentReadiness(assessment);
  return <div className="space-y-6"><div className="grid gap-6 lg:grid-cols-2"><article className="rounded-xl border border-border bg-white p-5 shadow-none sm:p-6"><h3 className="text-lg font-semibold tracking-[-0.02em] text-primary">Assessment information</h3><dl className="mt-5 space-y-5"><Definition label="Assessment name">{assessment.name}</Definition><Definition label="Description"><span className="font-normal leading-6 text-foreground">{assessment.description || "No description provided."}</span></Definition><Definition label="Assigned role">{roleTitle}</Definition><Definition label="Status"><StatusBadge status={assessment.status} /></Definition><Definition label="Last updated">{assessment.lastUpdatedLabel}</Definition></dl></article><article className="rounded-xl border border-border bg-white p-5 shadow-none sm:p-6"><h3 className="text-lg font-semibold tracking-[-0.02em] text-primary">Configuration status</h3><dl className="mt-5 space-y-5"><Definition label="Assigned questions">{assessment.isUnderDevelopment ? `${readiness.total} of approximately ${assessment.plannedQuestionCount ?? "—"} specified` : readiness.total}</Definition><Definition label="Scoring readiness"><span className={readiness.ready ? "text-status-success-strong" : "text-[#765d22]"}>{readiness.configured} of {readiness.total} configured</span></Definition><Definition label="Questions awaiting configuration">{readiness.incomplete}</Definition><Definition label="Assessment state"><span className="font-normal leading-6 text-foreground">{assessment.isUnderDevelopment ? "Draft remains under development; missing framework questions will be added in a later migration." : readiness.ready ? "All selected questions have scoring configuration." : "Scoring configuration remains incomplete."}</span></Definition></dl></article></div>{assessment.isUnderDevelopment ? <article className="flex gap-3 rounded-xl border border-[#eadfbd] bg-[#fffaf0] px-4 py-4"><AlertTriangle className="mt-0.5 size-[18px] shrink-0 text-[#765d22]" /><div><p className="text-sm font-semibold text-primary">Draft under development</p><p className="mt-1 text-[13px] leading-6 text-[#765d22]">{readiness.total} of approximately {assessment.plannedQuestionCount ?? "—"} framework questions are currently specified. This inactive draft is not exposed to applicants.</p></div></article> : readiness.incomplete > 0 ? <article className="flex gap-3 rounded-xl border border-[#eadfbd] bg-[#fffaf0] px-4 py-4"><AlertTriangle className="mt-0.5 size-[18px] shrink-0 text-[#765d22]" /><div><p className="text-sm font-semibold text-primary">Scoring configuration required</p><p className="mt-1 text-[13px] leading-6 text-[#765d22]">This assessment contains questions without scoring configuration. Candidate scoring will remain unavailable until configuration is complete.</p></div></article> : null}</div>;
}

function QuestionsTab({ assessment, onNavigate }: { assessment: AdminAssessment; onNavigate: (path: string) => void }) {
  const questions = getAssessmentQuestions(assessment);
  return <section><div className="flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between"><div><h3 className="text-xl font-semibold tracking-[-0.025em] text-primary">Assessment questions</h3><p className="mt-1 text-sm text-muted-foreground">{assessment.isUnderDevelopment ? "Questions are retained in the deliberate draft order for future applicant delivery." : "Questions appear in the order presented to applicants."}</p></div><p className="text-[13px] text-muted-foreground">{questions.length} assigned</p></div>{questions.length ? <article className="mt-5 rounded-xl border border-border bg-white p-4 shadow-none sm:p-5"><ol className="divide-y divide-border">{questions.map((question, index) => <QuestionRow index={index} key={question.id} onNavigate={onNavigate} question={question} />)}</ol></article> : <article className="mt-5 rounded-xl border border-dashed border-portal-border-strong bg-white px-6 py-10 text-center"><h4 className="text-base font-semibold text-primary">No questions added</h4><p className="mt-2 text-sm text-muted-foreground">Add questions from the Question Bank to build this assessment.</p></article>}</section>;
}
function QuestionRow({ question, index, onNavigate }: { question: QuestionBankQuestion; index: number; onNavigate: (path: string) => void }) { const configured = hasQuestionConfiguration(question); return <li className="py-5 first:pt-1 last:pb-1"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-x-3 gap-y-2"><span className="text-[12px] font-semibold uppercase tracking-[0.08em] text-muted-foreground">{String(index + 1).padStart(2, "0")} · {question.reference}</span><ScoringState configured={configured} /></div><p className="mt-2 text-sm font-medium leading-6 text-primary">{question.question}</p><p className="mt-2 text-[13px] text-muted-foreground">{question.competency}</p></div><button className="shrink-0 text-left text-[13px] font-medium text-portal-blue transition-colors hover:text-primary hover:underline sm:text-right" onClick={() => onNavigate(configured ? `/admin/questions/${question.id}` : `/admin/questions/${question.id}/edit`)} type="button">{configured ? "View question" : "Configure scoring"}</button></div></li>; }

export default function AdminAssessmentDetail() {
  const [, params] = useRoute("/admin/assessments/:assessmentSlug"); const [, setLocation] = useLocation(); const assessment = getAdminAssessment(params?.assessmentSlug ?? "");
  const rolesState = useAdminRoles();
  if (!assessment) return <AdminShell title="Assessments"><section className="py-8"><h2 className="text-2xl font-semibold tracking-[-0.03em] text-primary">Assessment not found</h2><p className="mt-2 text-sm text-muted-foreground">The requested assessment could not be found.</p><FoundationButton className="mt-6" onClick={() => setLocation("/admin/assessments")} variant="secondary">Back to Assessments</FoundationButton></section></AdminShell>;
  const readiness = getAssessmentReadiness(assessment);
  const roleTitle = rolesState.status === "loading" ? "Loading…" : (rolesState.data ?? []).find((role) => role.id === assessment.roleId)?.title ?? "Role unavailable";
  const initialTab = typeof window !== "undefined" && window.location.hash === "#questions" ? "questions" : "overview";
  return <AdminShell title="Assessments"><button className="inline-flex items-center gap-2 text-[13px] font-medium text-muted-foreground transition-colors hover:text-primary" onClick={() => setLocation("/admin/assessments")} type="button"><ArrowLeft className="size-4" />Back to Assessments</button><article className="mt-5 rounded-xl border border-border bg-white p-5 shadow-none sm:p-6"><div className="flex flex-col gap-5 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-[12px] font-medium text-muted-foreground">Assessment configuration</p><h2 className="mt-2 text-2xl font-semibold tracking-[-0.03em] text-primary sm:text-3xl">{assessment.name}</h2><div className="mt-3 flex flex-wrap items-center gap-x-4 gap-y-2 text-[13px] text-muted-foreground"><span className="font-medium text-primary">{roleTitle}</span><span>{assessment.isUnderDevelopment ? `${readiness.total} of approximately ${assessment.plannedQuestionCount ?? "—"} specified` : `${readiness.total} selected questions`}</span><span>{readiness.configured} of {readiness.total} configured</span><StatusBadge status={assessment.status} /></div></div><div className="flex flex-wrap gap-2"><FoundationButton onClick={() => setLocation(`/admin/assessments/${assessment.slug}/edit`)} variant="secondary"><Pencil className="size-4" />Edit assessment</FoundationButton>{assessment.isUnderDevelopment ? <FoundationButton onClick={() => setLocation(`/admin/assessments/${assessment.slug}/preview`)}><Eye className="size-4" />Preview candidate experience</FoundationButton> : null}</div></div></article><Tabs className="mt-6" defaultValue={initialTab}><div className="overflow-x-auto pb-1"><TabsList><TabsTrigger value="overview">Overview</TabsTrigger><TabsTrigger value="questions">Questions</TabsTrigger></TabsList></div><TabsContent value="overview"><OverviewTab assessment={assessment} roleTitle={roleTitle} /></TabsContent><TabsContent value="questions"><QuestionsTab assessment={assessment} onNavigate={setLocation} /></TabsContent></Tabs></AdminShell>;
}
