/** Quiet Authority CV Evidence review: structured Admin-only manual evidence review with no weighted, CV, or overall-fit score. */
import { FoundationButton, FoundationSelect, FoundationTextarea } from "@/components/foundation/ui";
import { getCandidateCvEvidenceReviewSummary, saveCandidateCvEvidenceReview, type CandidateCriterionEvidence, type CvEvidenceItem } from "@/lib/candidateCvEvidenceData";
import { FileText, Eye, Info, Save } from "lucide-react";
import { useEffect, useState } from "react";
import { toast } from "sonner";
import type { AdminApplication } from "@/lib/adminMockData";
import type { CvEvidenceCriterion } from "@/lib/roleCvCriteriaData";

const ratings = [
  [0, "No relevant evidence"], [1, "Very limited evidence"], [2, "Basic evidence"], [3, "Moderate evidence"], [4, "Strong evidence"], [5, "Very strong evidence"],
] as const;

function ReviewPill({ complete, ratedCount, totalCount }: { complete: boolean; ratedCount: number; totalCount: number }) { return <div><p className="text-[12px] font-medium text-muted-foreground">Review status</p><p className={`mt-1 text-sm font-semibold ${complete ? "text-status-success-strong" : "text-[#765d22]"}`}>{complete ? "Complete" : "Incomplete"}</p><p className="mt-2 text-[13px] text-primary">{ratedCount} of {totalCount} criteria rated</p></div>; }

function RatingGuide() { return <article className="rounded-xl border border-border bg-white p-5 shadow-none"><h3 className="text-lg font-semibold tracking-[-0.02em] text-primary">Evidence rating guide</h3><dl className="mt-5 space-y-3 text-[13px]">{ratings.map(([value, label]) => <div className="flex justify-between gap-4" key={value}><dt className="font-semibold text-primary">{value}</dt><dd className="text-right text-muted-foreground">{label}</dd></div>)}</dl><p className="mt-5 border-t border-border pt-4 text-[13px] leading-5 text-muted-foreground">Rate the strength of evidence in the CV, not the candidate's overall suitability.</p></article>; }

function CandidateCvReference({ application, onPreview }: { application: AdminApplication; onPreview: () => void }) {
  if (!application.cv) return <article className="rounded-xl border border-border bg-white p-5 shadow-none"><h3 className="text-lg font-semibold tracking-[-0.02em] text-primary">Candidate CV</h3><p className="mt-4 text-sm font-medium text-primary">CV not available</p><p className="mt-1 text-[13px] leading-5 text-muted-foreground">No CV information is currently associated with this demo application.</p></article>;
  return <article className="rounded-xl border border-border bg-white p-5 shadow-none"><h3 className="text-lg font-semibold tracking-[-0.02em] text-primary">Candidate CV</h3><div className="mt-5 flex min-w-0 gap-3"><span className="flex size-9 shrink-0 items-center justify-center rounded-lg bg-portal-blue-soft text-portal-blue"><FileText className="size-4.5" /></span><div className="min-w-0"><p className="break-words text-sm font-semibold text-primary">{application.cv.fileName}</p><p className="mt-1 text-[13px] text-muted-foreground">{application.cv.fileType} · {application.cv.fileSize}</p></div></div><FoundationButton className="mt-5 w-full" onClick={onPreview} size="sm" variant="secondary"><Eye className="size-3.5" />View CV</FoundationButton></article>;
}

function EvidenceItems({ items }: { items: CvEvidenceItem[] }) {
  if (!items.length) return <div className="mt-4 rounded-lg border border-border bg-portal-surface px-4 py-3"><p className="text-[13px] font-semibold text-primary">Not clearly evidenced</p><p className="mt-1 text-[13px] leading-5 text-muted-foreground">The candidate's CV does not currently provide clear evidence against this criterion.</p></div>;
  return <div className="mt-4 space-y-3">{items.map((item, index) => <div className="rounded-lg border border-portal-blue/15 bg-portal-blue-soft/45 px-4 py-3" key={`${item.source}-${index}`}><div className="flex flex-wrap items-baseline justify-between gap-x-4 gap-y-1"><p className="text-[13px] font-semibold text-primary">{item.source}</p>{item.period ? <p className="text-[12px] font-medium text-muted-foreground">{item.period}</p> : null}</div><p className="mt-2 text-[13px] leading-5 text-primary">{item.text}</p></div>)}</div>;
}

function CriterionReview({ criterion, index, review, onChange }: { criterion: CvEvidenceCriterion; index: number; review: CandidateCriterionEvidence; onChange: (next: CandidateCriterionEvidence) => void }) {
  return <section className="py-6 first:pt-1 last:pb-1"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-x-3 gap-y-1"><span className="text-[12px] font-semibold uppercase tracking-[0.09em] text-portal-blue">{String(index + 1).padStart(2, "0")}</span><span className="text-[12px] text-muted-foreground">Weight {criterion.weight}%</span></div><h4 className="mt-2 text-base font-semibold leading-6 text-primary">{criterion.name}</h4><p className="mt-2 text-[13px] leading-5 text-muted-foreground">{criterion.description}</p></div><label className="w-full shrink-0 sm:w-[205px]"><span className="text-[12px] font-medium text-muted-foreground">Evidence rating</span><FoundationSelect className="mt-1.5 h-10" onChange={(event) => onChange({ ...review, rating: event.target.value === "" ? null : Number(event.target.value) })} value={review.rating ?? ""}><option value="">Unrated</option>{ratings.map(([value, label]) => <option key={value} value={value}>{value} — {label}</option>)}</FoundationSelect></label></div><div className="mt-5"><p className="text-[12px] font-semibold uppercase tracking-[0.08em] text-muted-foreground">CV Evidence</p><EvidenceItems items={review.evidenceItems} /></div><label className="mt-4 block"><span className="text-[12px] font-medium text-muted-foreground">Review note</span><FoundationTextarea className="mt-1.5 min-h-20" onChange={(event) => onChange({ ...review, reviewNote: event.target.value })} placeholder="Add an internal note about this evidence" value={review.reviewNote} /></label></section>;
}

export function CandidateCvEvidenceTab({ application, onPreview }: { application: AdminApplication; onPreview: () => void }) {
  const initial = () => getCandidateCvEvidenceReviewSummary(application.id); const [reviewState, setReviewState] = useState(initial); const [dirty, setDirty] = useState(false);
  useEffect(() => { setReviewState(getCandidateCvEvidenceReviewSummary(application.id)); setDirty(false); }, [application.id]);
  const updateReview = (criterionId: string, next: CandidateCriterionEvidence) => { setReviewState((current) => ({ ...current, reviews: current.reviews.map((review) => review.criterionId === criterionId ? next : review), ratedCount: current.reviews.filter((review) => review.criterionId === criterionId ? next.rating !== null : review.rating !== null).length, complete: current.activeCriteria.length > 0 && current.reviews.filter((review) => review.criterionId === criterionId ? next.rating !== null : review.rating !== null).length === current.activeCriteria.length, status: current.reviews.filter((review) => review.criterionId === criterionId ? next.rating !== null : review.rating !== null).length === 0 ? "Not Started" : current.reviews.filter((review) => review.criterionId === criterionId ? next.rating !== null : review.rating !== null).length === current.activeCriteria.length ? "Complete" : "In Progress" })); setDirty(true); };
  const save = () => { saveCandidateCvEvidenceReview(application.id, reviewState.reviews); setDirty(false); toast.success("CV evidence review saved."); };
  return <section><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><h3 className="text-xl font-semibold tracking-[-0.025em] text-primary">CV Evidence Review</h3><p className="mt-1 text-sm text-muted-foreground">Review the candidate's CV against the criteria configured for the Business Development Manager role.</p></div><p className="text-[13px] font-semibold text-primary">{reviewState.totalCount} criteria</p></div><article className="mt-5 flex gap-3 rounded-xl border border-portal-blue/15 bg-portal-blue-soft/50 px-4 py-4"><Info className="mt-0.5 size-[18px] shrink-0 text-portal-blue" /><div><h4 className="text-sm font-semibold text-primary">Evidence-based review</h4><p className="mt-1 text-[13px] leading-6 text-muted-foreground">Rate each criterion based on the evidence available in the candidate's CV. Use “Not clearly evidenced” where the CV does not provide enough information to support a stronger rating.</p></div></article><div className="mt-6 grid gap-6 xl:grid-cols-[minmax(0,70fr)_minmax(250px,30fr)]"><article className="rounded-xl border border-border bg-white p-5 shadow-none sm:p-6"><div className="flex flex-col gap-3 border-b border-border pb-5 sm:flex-row sm:items-start sm:justify-between"><div><h4 className="text-base font-semibold text-primary">Criterion evidence review</h4><p className="mt-1 text-[13px] text-muted-foreground">{reviewState.activeCriteria.length} active criteria in configured order.</p></div><ReviewPill complete={reviewState.complete} ratedCount={reviewState.ratedCount} totalCount={reviewState.totalCount} /></div><div className="divide-y divide-border">{reviewState.activeCriteria.map((criterion, index) => { const review = reviewState.reviews.find((item) => item.criterionId === criterion.id) ?? { criterionId: criterion.id, evidenceItems: [], rating: null, reviewNote: "" }; return <CriterionReview criterion={criterion} index={index} key={criterion.id} onChange={(next) => updateReview(criterion.id, next)} review={review} />; })}</div></article><aside className="space-y-5"><CandidateCvReference application={application} onPreview={onPreview} /><article className="rounded-xl border border-border bg-white p-5 shadow-none"><ReviewPill complete={reviewState.complete} ratedCount={reviewState.ratedCount} totalCount={reviewState.totalCount} /><p className="mt-4 border-t border-border pt-4 text-[13px] leading-5 text-muted-foreground">{reviewState.complete ? "Review complete" : "Review incomplete"}</p></article><RatingGuide /></aside></div><div className="mt-6 flex flex-col gap-3 border-t border-border pt-5 sm:flex-row sm:items-center sm:justify-between"><p className="text-[13px] text-muted-foreground">{dirty ? "Unsaved CV review changes." : "Ratings and notes are visible to Admin only."}</p><FoundationButton disabled={!dirty} onClick={save} type="button"><Save className="size-4" />Save CV review</FoundationButton></div></section>;
}
